CREATE TABLE COMUNA(ID_COMUNA NUMBER(2),
                    NOM_COMUNA VARCHAR2(30)
                    );
                    


ALTER TABLE COMUNA ADD CONSTRAINT ID_COMUNA_PK PRIMARY KEY (ID_COMUNA);                    
ALTER TABLE COMUNA MODIFY NOM_COMUNA CONSTRAINT DESC_NOM_COMUN NOT NULL;  


CREATE SEQUENCE COMU_ID_SEQ
START WITH 0
MINVALUE 0
MAXVALUE 999999
INCREMENT BY 3;

DROP SEQUENCE COMU_ID_SEQ; 

INSERT INTO COMUNA VALUES(COMU_ID_SEQ.NEXTVAL,'SANTIAGO CENTRO');
INSERT INTO COMUNA VALUES(COMU_ID_SEQ.NEXTVAL,'LOS ANGELES');





CREATE TABLE CAMION (NUM_PATENTE NUMBER (6),
                     ID_TIPO_CAMION NUMBER(6)
                     );
DROP TABLE CAMION;                     
                     
ALTER TABLE CAMION ADD CONSTRAINT NUM_PATENTE_PK PRIMARY KEY (NUM_PATENTE);
ALTER TABLE CAMION MODIFY ID_TIPO_CAMION CONSTRAINT DESC_TIPO_CAMION NOT NULL;
ALTER TABLE CAMION ADD CONSTRAINT ID_TIPO_CAMIONC_FK FOREIGN KEY (ID_TIPO_CAMION)REFERENCES TIPO_CAMION(ID_TIPO_CAMION);
                     

CREATE TABLE TIPO_CAMION (ID_TIPO_CAMION NUMBER(6),
                          NUM_PATENTE NUMBER(6),
                          VAL_ARRIENDO_DIA VARCHAR2 (7),
                          VAL_GARANT_DIA VARCHAR2 (6),
                          MARCA VARCHAR2 (20),
                          COLOR VARCHAR2 (15),
                          MOTOR VARCHAR2 (5),
                          ANIO NUMBER(4)
                          
                          );
                          
ALTER TABLE TIPO_CAMION ADD CONSTRAINT ID_TIPO_CAMION_PK PRIMARY KEY (ID_TIPO_CAMION); 
ALTER TABLE TIPO_CAMION ADD CONSTRAINT NUM_PATENTT_FK FOREIGN KEY (NUM_PATENTE)REFERENCES CAMION(NUM_PATENTE);

ALTER TABLE TIPO_CAMION MODIFY NUM_PATENTE CONSTRAINT DESC_NUM_PATENTE NOT NULL;
ALTER TABLE TIPO_CAMION MODIFY VAL_ARRIENDO_DIA  CONSTRAINT DESC_VAL_ARRIENDO_DIA  NOT NULL;
ALTER TABLE TIPO_CAMION MODIFY VAL_GARANT_DIA CONSTRAINT DESC_VAL_GARANT_DIA NOT NULL;
ALTER TABLE TIPO_CAMION MODIFY MARCA CONSTRAINT DESC_MARCA NOT NULL;
ALTER TABLE TIPO_CAMION MODIFY MOTOR CONSTRAINT DESC_MOTOR NOT NULL;




CREATE TABLE ARRIENDO_CAMION (ID_ARRIENDO NUMBER (7),
                              
                              ID_CLIENT NUMBER(10),
                              FECH_INI_ARRIENDO VARCHAR2(6),
                              DIAS_ARRIENDO NUMBER (6),
                              FECH_DEVOLUCION VARCHAR2 (6)
                              );
DROP TABLE ARRIENDO_CAMION;

CREATE SEQUENCE ARRIENDO_SEQ
START WITH 0
MINVALUE 0
MAXVALUE 999999
INCREMENT BY 10;

INSERT INTO ARRIENDO_CAMION VALUES(ARRIENDO_SEQ.NEXTVAL,66666666,'5155',545,'55');                              

ALTER TABLE ARRIENDO_CAMION ADD CONSTRAINT ID_ARRIENDO_PK PRIMARY KEY (ID_ARRIENDO);
ALTER TABLE ARRIENDO_CAMION MODIFY ID_CLIENT CONSTRAINT DESC_ID_CLIENT NOT NULL;
ALTER TABLE ARRIENDO_CAMION MODIFY FECH_INI_ARRIENDO CONSTRAINT DESC_FECH_INI_ARRIENDO NOT NULL;
ALTER TABLE ARRIENDO_CAMION MODIFY DIAS_ARRIENDO CONSTRAINT DESC_DIAS_ARRIENDO NOT NULL;
ALTER TABLE ARRIENDO_CAMION MODIFY FECH_DEVOLUCION CONSTRAINT DESC_FECH_DEVOLUCION NOT NULL;



ALTER TABLE ARRIENDO_CAMION ADD CONSTRAINT ID_CLIENA_FK FOREIGN KEY (ID_CLIENT)REFERENCES CLIENTE(ID_CLIENT);
ALTER TABLE ARRIENDO_CAMION MODIFY FECH_INI_ARRIENDO CONSTRAINT DESC_FECH_INI_ARRIENDO NOT NULL;



                           
CREATE TABLE EMPLEADO (ID_EMPLEADO NUMBER(10),
                       RUT_EMPLEADO NUMBER(8),
                       DV_EMP VARCHAR2(1),
                       APPAT_EMP VARCHAR2(30),
                       APMAT_EMP VARCHAR2 (30),
                       PNOM_EMP VARCHAR2 (25),
                       SNOM_EMP VARCHAR2 (25),
                       DIRECC_EMP VARCHAR2 (60),
                       SEX_EMP CHAR(1),
                       CEL_EMP NUMBER(15),
                       FONO_FIJO NUMBER(15),
                       FECH_NACI DATE,
                       FECH_CONTRATO DATE,
                       SUELDO_BASE NUMBER(7),
                       COMISION NUMBER (7),
                       ID_COMUNA NUMBER (2),
                       ID_TIPO_SAL NUMBER(6),
                       ID_ESTADO_CIVIL NUMBER (6)
                       
                       );

CREATE SEQUENCE EMPLE_SEQ
START WITH 100
MINVALUE 0
MAXVALUE 999999
INCREMENT BY 2;

ALTER TABLE EMPLEADO ADD CONSTRAINT ID_EMPLEADO_PK PRIMARY KEY (ID_EMPLEADO);
ALTER TABLE EMPLEADO ADD CONSTRAINT ID_COMUNA_FK FOREIGN KEY (ID_COMUNA)REFERENCES COMUNA(ID_COMUNA);
ALTER TABLE EMPLEADO ADD CONSTRAINT ID_TIPO_SAL_FK FOREIGN KEY (ID_TIPO_SAL)REFERENCES TIPO_SALUD(ID_TIPO_SAL);
ALTER TABLE EMPLEADO ADD CONSTRAINT ID_ESTADO_CIVIL_FK FOREIGN KEY (ID_ESTADO_CIVIL)REFERENCES ESTADO_CIVIL(ID_ESTADO_CIVIL);

ALTER TABLE EMPLEADO MODIFY RUT_EMPLEADO CONSTRAINT DESC_RUT_EMPLEADO NOT NULL;
ALTER TABLE EMPLEADO MODIFY DV_EMP CONSTRAINT DESC_DV_EMP NOT NULL;
ALTER TABLE EMPLEADO MODIFY APPAT_EMP CONSTRAINT DESC_APPAT_EMP NOT NULL;
ALTER TABLE EMPLEADO MODIFY APMAT_EMP CONSTRAINT DESC_APMAT_EMP NOT NULL;
ALTER TABLE EMPLEADO MODIFY PNOM_EMP CONSTRAINT DESC_PNOM_EMP NOT NULL;
ALTER TABLE EMPLEADO MODIFY DIRECC_EMP CONSTRAINT DESC_DIRECC_EMP NOT NULL;
ALTER TABLE EMPLEADO MODIFY SEX_EMP CONSTRAINT DESC_SEX_EMP NOT NULL;
ALTER TABLE EMPLEADO MODIFY CEL_EMP CONSTRAINT DESC_CEL_EMP NOT NULL;
ALTER TABLE EMPLEADO MODIFY FONO_FIJO CONSTRAINT DESC_FONO_FIJO NOT NULL;
ALTER TABLE EMPLEADO MODIFY FECH_NACI CONSTRAINT DESC_FECH_NACI NOT NULL;
ALTER TABLE EMPLEADO MODIFY FECH_CONTRATO CONSTRAINT DESC_FECH_CONTRATO NOT NULL;
ALTER TABLE EMPLEADO MODIFY SUELDO_BASE CONSTRAINT DESC_SUELDO_BASE NOT NULL;
ALTER TABLE EMPLEADO MODIFY COMISION CONSTRAINT DESC_COMISION NOT NULL;
ALTER TABLE EMPLEADO MODIFY ID_TIPO_SAL CONSTRAINT DESC_ID_TIPO_SAL NOT NULL;
ALTER TABLE EMPLEADO MODIFY ID_ESTADO_CIVIL CONSTRAINT DESC_ID_ESTADO_CIVIL NOT NULL;

                       

CREATE TABLE ESTADO_CIVIL (ID_ESTADO_CIVIL NUMBER(6),
                           ESTADO_CIVIL VARCHAR2(25)
                           );

ALTER TABLE ESTADO_CIVIL ADD CONSTRAINT ID_ESTADO_CIVIL_PK PRIMARY KEY (ID_ESTADO_CIVIL);  
ALTER TABLE ESTADO_CIVIL MODIFY ESTADO_CIVIL CONSTRAINT DESC_ESTADO_CIVIL NOT NULL;

INSERT INTO ESTADO_CIVIL VALUES(ARRIENDO_SEQ.NEXTVAL,66666666,'5155',545,'55');  


CREATE TABLE TIPO_SALUD(ID_TIPO_SAL NUMBER(6),
                        DESCRIP_SAL VARCHAR2 (100),
                        PCT_SUELDO NUMBER(3,1)
                        );


ALTER TABLE TIPO_SALUD ADD CONSTRAINT ID_TIPO_SAL_PK PRIMARY KEY (ID_TIPO_SAL);
ALTER TABLE TIPO_SALUD MODIFY DESCRIP_SAL CONSTRAINT DESC_DESCRIP_SAL NOT NULL;
ALTER TABLE TIPO_SALUD MODIFY PCT_SUELDO CONSTRAINT DESC_PCT_SUELDO NOT NULL;

CREATE SEQUENCE SALUD_SEQ
START WITH 300
MINVALUE 0
MAXVALUE 999999
INCREMENT BY 5;



INSERT INTO TIPO_SALUD VALUES(SALUD_SEQ.NEXTVAL,'FONASA',2.1);                        

SELECT *FROM TIPO_SALUD;
                       
CREATE TABLE CLIENTE  (ID_CLIENT NUMBER(10),
                       RUT_CLIENT NUMBER(10),
                       DV_CLI VARCHAR2(1),
                       APPAT_CLI VARCHAR2(30),
                       APMAT_CLI VARCHAR2 (30),
                       PNOM_CLI VARCHAR2 (25),
                       SNOM_CLI VARCHAR2 (25),
                       DIRECC_CLI VARCHAR2 (60),
                       CEL_CLI NUMBER(15),
                       FONO_FIJO_CLI NUMBER(15),
                       RENTA VARCHAR2(7),
                       FECH_NACI_CLI DATE,
                       ID_COMUNA NUMBER (2),
                       ID_TIPO_CLI NUMBER(6),
                       ID_ESTADO_CIVIL NUMBER(6)
                       );




CREATE SEQUENCE CLIENTE_SEQ
START WITH 200
MINVALUE 0
MAXVALUE 999999
INCREMENT BY 20;

ALTER TABLE CLIENTE ADD CONSTRAINT ID_CLIENT_PK PRIMARY KEY (ID_CLIENT);                       
ALTER TABLE CLIENTE ADD CONSTRAINT ID_COMUNA_CLI_FK FOREIGN KEY (ID_COMUNA)REFERENCES COMUNA(ID_COMUNA);
ALTER TABLE CLIENTE ADD CONSTRAINT ID_TIPO_CLIE_FK FOREIGN KEY (ID_TIPO_CLI)REFERENCES TIPO_CLIENTE(ID_TIPO_CLI);
ALTER TABLE CLIENTE ADD CONSTRAINT ID_ESTADO_CIVIL_CLI_FK FOREIGN KEY (ID_ESTADO_CIVIL)REFERENCES ESTADO_CIVIL(ID_ESTADO_CIVIL);

ALTER TABLE CLIENTE MODIFY RUT_CLIENT CONSTRAINT DESC_RUT_CLIENT NOT NULL;
ALTER TABLE CLIENTE MODIFY DV_CLI CONSTRAINT DESC_DV_CLI NOT NULL;
ALTER TABLE CLIENTE MODIFY APPAT_CLI CONSTRAINT DESC_APPAT_CLI NOT NULL;
ALTER TABLE CLIENTE MODIFY APMAT_CLI CONSTRAINT DESC_APMAT_CLI NOT NULL;
ALTER TABLE CLIENTE MODIFY PNOM_CLI CONSTRAINT DESC_PNOM_CLI NOT NULL;
ALTER TABLE CLIENTE MODIFY DIRECC_CLI CONSTRAINT DESC_DIRECC_CLI NOT NULL;
ALTER TABLE CLIENTE MODIFY CEL_CLI CONSTRAINT DESC_CEL_CLI NOT NULL;
ALTER TABLE CLIENTE MODIFY FONO_FIJO_CLI CONSTRAINT DESC_FONO_FIJO_CLI NOT NULL;
ALTER TABLE CLIENTE MODIFY RENTA CONSTRAINT DESC_RENTA NOT NULL;
ALTER TABLE CLIENTE MODIFY FECH_NACI_CLI CONSTRAINT DESC_FECH_NACI_CLI NOT NULL;
ALTER TABLE CLIENTE MODIFY ID_TIPO_CLI CONSTRAINT DESC_ID_TIPO_CLI NOT NULL;
ALTER TABLE CLIENTE MODIFY ID_ESTADO_CIVIL CONSTRAINT DESC_ID_ESTADOO_CIVIL NOT NULL;
ALTER TABLE CLIENTE MODIFY ID_COMUNA CONSTRAINT DESC_ID_COMUN NOT NULL;


INSERT INTO CLIENTE VALUES(CLIENTE_SEQ.NEXTVAL,66666666,'5','ROJAS','VEGA','ANDRES','JUAN','BUENAVENTURA',545,55,'SI','11-08-1989',2,454,2); 

SELECT*FROM CLIENTE;

CREATE TABLE TIPO_CLIENTE(ID_TIPO_CLI NUMBER(6),
                          TIPO_CLIENTE VARCHAR2 (15)
                          );
ALTER TABLE TIPO_CLIENTE ADD CONSTRAINT TIPO_CLIENTE_PK PRIMARY KEY (ID_TIPO_CLI);  
ALTER TABLE TIPO_CLIENTE MODIFY TIPO_CLIENTE CONSTRAINT DESC_TIPO_CLIENTE NOT NULL;


CREATE TABLE FACTURA(ID_FACTURA NUMBER(7),
                     ID_CLIENT NUMBER(10),
                     ID_DETALLE NUMBER(7),
                     FECHA_EMISION DATE
                     );
                 
ALTER TABLE FACTURA ADD CONSTRAINT ID_FACTURA_PK PRIMARY KEY (ID_FACTURA);                       
ALTER TABLE FACTURA ADD CONSTRAINT RUT_CLIENTF_FK FOREIGN KEY (ID_CLIENT)REFERENCES CLIENTE(ID_CLIENT);
ALTER TABLE FACTURA ADD CONSTRAINT DETA_FACT_FK FOREIGN KEY (ID_DETALLE)REFERENCES DETA_FACT(ID_DETALLE);

ALTER TABLE FACTURA MODIFY ID_CLIENT CONSTRAINT DESC_ID_CLIENTE NOT NULL;
ALTER TABLE FACTURA MODIFY ID_DETALLE CONSTRAINT DESC_ID_DETALLE NOT NULL;
ALTER TABLE FACTURA MODIFY FECHA_EMISION CONSTRAINT DESC_FECHA_EMISION NOT NULL;




CREATE TABLE DETA_FACT (ID_DETALLE NUMBER(7),
                        ID_ARRIENDO NUMBER (7),
                        ID_EMPLEADO NUMBER(10),
                        ID_GARANTIA NUMBER(10),
                        TOTAL_NETO NUMBER(10),
                        TOTAL NUMBER(10)
                        );
                        
                        
                        
ALTER TABLE DETA_FACT ADD CONSTRAINT ID_DETA_PK PRIMARY KEY (ID_DETALLE);                       
ALTER TABLE DETA_FACT ADD CONSTRAINT ID_ARRIEND_FK FOREIGN KEY (ID_ARRIENDO)REFERENCES ARRIENDO_CAMION(ID_ARRIENDO);
ALTER TABLE DETA_FACT ADD CONSTRAINT ID_EMPLED_FK FOREIGN KEY (ID_EMPLEADO)REFERENCES EMPLEADO(ID_EMPLEADO);
ALTER TABLE DETA_FACT ADD CONSTRAINT ID_GARANTD_FK FOREIGN KEY (ID_GARANTIA)REFERENCES GARANTIA(ID_GARANTIA);    

ALTER TABLE DETA_FACT MODIFY ID_ARRIENDO CONSTRAINT DESC_ID_ARRIENDO NOT NULL;
ALTER TABLE DETA_FACT MODIFY ID_EMPLEADO CONSTRAINT DESC_ID_EMPLEADOD NOT NULL;
ALTER TABLE DETA_FACT MODIFY ID_GARANTIA CONSTRAINT DESC_ID_GARANTIAD NOT NULL;
ALTER TABLE DETA_FACT MODIFY TOTAL_NETO CONSTRAINT DESC_TOTAL_NETO NOT NULL;
ALTER TABLE DETA_FACT MODIFY TOTAL CONSTRAINT DESC_TOTAL NOT NULL;


CREATE TABLE GARANTIA (ID_GARANTIA NUMBER(7),
                       ID_INFORME NUMBER(6),
                       GARANT_TOTAL NUMBER (6)
                       ); 
                       
                         
ALTER TABLE GARANTIA ADD CONSTRAINT ID_GARANTIA_PK PRIMARY KEY (ID_GARANTIA);                            
ALTER TABLE GARANTIA ADD CONSTRAINT ID_INFORMEG_FK FOREIGN KEY (ID_INFORME)REFERENCES INFORME_GARANT(ID_INFORME);
ALTER TABLE GARANTIA MODIFY ID_INFORME CONSTRAINT DESC_INFORME NOT NULL;
ALTER TABLE GARANTIA MODIFY GARANT_TOTAL CONSTRAINT DESC_GARANT NOT NULL;

CREATE TABLE INFORME_GARANT(ID_INFORME NUMBER(6),
                            ID_EMPLEADO NUMBER(10),
                            INFORME VARCHAR2 (100)
                            );

ALTER TABLE INFORME_GARANT ADD CONSTRAINT ID_INFORME_PK PRIMARY KEY (ID_INFORME);  
ALTER TABLE INFORME_GARANT ADD CONSTRAINT ID_EMPLEADOI_FK FOREIGN KEY (ID_EMPLEADO)REFERENCES EMPLEADO(ID_EMPLEADO);
ALTER TABLE INFORME_GARANT MODIFY ID_EMPLEADO CONSTRAINT DESC_ID_EMPLEADOI NOT NULL;
ALTER TABLE INFORME_GARANT MODIFY INFORME CONSTRAINT DES_INFORMEI NOT NULL;